#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import os

from argparse import ArgumentParser


config_vars = [
    "LIVEKIT_API_KEY",
    "LIVEKIT_API_SECRET",
    "LIVEKIT_SERVER_URL",
    "POSTGRES_USER",
    "POSTGRES_PASSWORD",
    "POSTGRES_DB",
    "PGADMIN_DEFAULT_EMAIL",
    "PGADMIN_DEFAULT_PASSWORD",
    "PGADMIN_LISTEN_PORT",
    "DATABASE_URL",
    "APP_HOST",
    "APP_PORT",
    "NUM_ACTIX_WORKERS",
    "JWT_SECRET"
]


class ConfigGenerator:
    @staticmethod
    def run(filename):
        with open(filename, "w") as f:
            for var in config_vars:
                value = os.environ.get(var)
                if value is None:
                    raise ValueError(f"Environment variable {var} is not set")
                f.write(f'"{var}={value}"\n')



if __name__ == "__main__":
    parser = ArgumentParser(description="Generate config file")
    parser.add_argument("filename", help="Name of the file to generate")
    args = parser.parse_args()
    ConfigGenerator.run(args.filename)