version: "3.9"

services:
  postgres-syncflow-prod:
    image: postgres:14-alpine
    container_name: postgres-syncflow-prod
    ports:
      - "15433:5432"
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    env_file: ../crates/.env.prod.pgadmin

  pgadmin-prod:
    image: dpage/pgadmin4
    container_name: pgadmin-syncflow-prod
    ports:
      - "5051:81"
    env_file: ../crates/.env.prod.pgadmin
    depends_on:
      - postgres-syncflow-prod

  migrations-prod:
    build:
      context: ../crates
      dockerfile: ../docker/Dockerfile.migrations
    image: syncflow-migrations:latest
    container_name: syncflow-migrations-prod
    volumes:
      - ../crates/.env.prod.migration:/migrations/.env
    depends_on:
      - postgres-syncflow-prod

  api-syncflow-prod:
    build:
      context: ../crates
      dockerfile: ../docker/Dockerfile.api
    image: syncflow-api:latest
    container_name: syncflow-api-prod
    ports:
      - "8082:8082"
    env_file: ../crates/.env.prod
    depends_on:
      - migrations-prod

  syncflow-dashboard-prod:
    build:
      context: ../dashboard
      dockerfile: ../docker/Dockerfile.next
    image: syncflow-dashboard:latest
    container_name: syncflow-dashboard-prod
    ports:
      - "3000:3000"
    depends_on:
      - api-syncflow-prod

  syncflow-example-app-prod:
    build:
      context: ../examples/syncflow-demo-client
      dockerfile: ../../docker/Dockerfile.next
    image: syncflow-example-app:latest
    container_name: syncflow-example-app-prod
    ports:
      - "3001:3000"
    depends_on:
      - api-syncflow-prod

volumes:
  postgres-data-prod: