FROM rust:slim

WORKDIR /migrations

COPY ./infrastructure .

RUN apt-get update && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*

RUN cargo install diesel_cli --no-default-features --features postgres

CMD ["diesel", "migration", "run"]
